# Generated by Django 3.0.8 on 2023-07-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idpais', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('poblacion', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
