# Generated by Django 3.0.8 on 2023-07-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230720_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('ideditorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=50)),
                ('imagen', models.ImageField(default='null', upload_to='')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
